### ISSUE TITLE
try.docopt.org not properly handling required arguments

### ISSUE THREAD

**Issue by hawkeyej** [docopt/try.docopt.org#4]
Hi All,

The second command `ship <name> move` is returning an array for the `<name>` argument even though it's declared as a single argument. It looks like it is a carry over from the `ship new` command that does take multiple `<name>` arguments.

`ship <name> move` should not return an array for `<name>`.

Regards

**Comment by keleshev** [comment]
This is actually correct. Docopt makes sure that type of each value is same, no matter which pattern matched. For each element (command, option, argument) docopt finds the least general type that can represent all possible matched values. Because another sub-pattern contains `<name>...` with ellipsis, it figures that the least general type to represent `<name>` is a list of strings.

First example:

``` docopt
usage: prog
       prog <name>
```

``` json
{
  "<name>": null
}
```

Second example:

``` docopt
usage: prog
       prog <name>
       prog <name>...
```

``` json
{
  "<name>": []
}
```

**Comment by hawkeyej** [comment]
But that is not the way the usage is structured.

```
Usage:
    naval_fate.py ship new '<name>'...
    naval_fate.py ship '<name>' move '<x>' '<y>' [--speed=<kn>]

The first one is "ship new '<name>'...", which should allow multiple arguments
The second is "ship '<name>' move", which should not allow multiple arguments.
```

These are by no means subsets of one another, as is your example. The interveaning argument should be specific to the "move" command and not modeled after the "new" command. At least that is my opinion, as I find it confusing that the "ship <name> move" format appears to me that a single argument is required and not multiple. If multiple arguments are allowed, this makes the syntax more confusing.

P.S. How do I get less than signs in the text?

**Comment by BurntSushi** [comment]
@hawkeyej The type of each item is determined by examining _all_ patterns.

The alternative isn't really tenable because you'll end up with differently typed values in the returned dictionary depending on which pattern was matched.

**Comment by BurntSushi** [comment]
@hawkeyej 

> P.S. How do I get less than signs in the text?

Use fenced code blocks. I edited your comment with the fix. (Click edit on it and you'll see the syntax.)

**Comment by hawkeyej** [comment]
Thanks Guys.

docopt is the only way to go....
